export type FieldType = 'string' | 'number' | 'currency' | 'date' | 'boolean' | 'lookup' | 'percentage';

export type FieldCategory =
  | 'identification'
  | 'dates'
  | 'locations'
  | 'financial'
  | 'operational'
  | 'classification'
  | 'carrier'
  | 'accessorials'
  | 'items'
  | 'customer';

export interface LookupConfig {
  table: string;
  keyField: string;
  displayField: string;
  alternateField?: string;
}

export interface FieldDefinition {
  id: string;
  column: string;
  label: string;
  type: FieldType;
  category: FieldCategory;
  description?: string;
  lookup?: LookupConfig;
  isDefault?: boolean;
  availableForGrouping?: boolean;
  availableForAggregation?: boolean;
  defaultAggregation?: 'sum' | 'avg' | 'count' | 'min' | 'max';
  adminOnly?: boolean;
  sourceTable?: string;
}

export const SHIPMENT_FIELDS: FieldDefinition[] = [
  {
    id: 'load_id',
    column: 'load_id',
    label: 'Load ID',
    type: 'number',
    category: 'identification',
    description: 'Unique shipment identifier',
    isDefault: true,
    availableForGrouping: false,
    availableForAggregation: false,
  },
  {
    id: 'client_load_id',
    column: 'client_load_id',
    label: 'Client Load ID',
    type: 'number',
    category: 'identification',
    description: 'Client-specific load number',
  },
  {
    id: 'reference_number',
    column: 'reference_number',
    label: 'Reference #',
    type: 'string',
    category: 'identification',
    description: 'Customer reference number',
  },
  {
    id: 'bol_number',
    column: 'bol_number',
    label: 'BOL #',
    type: 'string',
    category: 'identification',
    description: 'Bill of Lading number',
  },
  {
    id: 'po_reference',
    column: 'po_reference',
    label: 'PO Reference',
    type: 'string',
    category: 'identification',
    description: 'Purchase order reference',
  },
  {
    id: 'quote_number',
    column: 'quote_number',
    label: 'Quote #',
    type: 'string',
    category: 'identification',
    description: 'Quote/rate confirmation number',
  },
  {
    id: 'shipper_number',
    column: 'shipper_number',
    label: 'Shipper #',
    type: 'string',
    category: 'identification',
    description: 'Shipper ID number',
  },
  {
    id: 'pickup_number',
    column: 'pickup_number',
    label: 'Pickup #',
    type: 'string',
    category: 'identification',
    description: 'Pickup confirmation number',
  },

  {
    id: 'mode_id',
    column: 'mode_id',
    label: 'Mode',
    type: 'lookup',
    category: 'classification',
    description: 'Transportation mode (LTL, TL, Parcel, etc)',
    lookup: {
      table: 'shipment_mode',
      keyField: 'mode_id',
      displayField: 'mode_code',
      alternateField: 'mode_name',
    },
    availableForGrouping: true,
    availableForAggregation: false,
  },
  {
    id: 'status_id',
    column: 'status_id',
    label: 'Status',
    type: 'lookup',
    category: 'classification',
    description: 'Current shipment status',
    lookup: {
      table: 'shipment_status',
      keyField: 'status_id',
      displayField: 'status_code',
      alternateField: 'status_name',
    },
    availableForGrouping: true,
    availableForAggregation: false,
  },
  {
    id: 'status_code',
    column: 'status_code',
    label: 'Status Code',
    type: 'string',
    category: 'classification',
    description: 'Status code shorthand',
    availableForGrouping: true,
  },
  {
    id: 'status_description',
    column: 'status_description',
    label: 'Status Description',
    type: 'string',
    category: 'classification',
    description: 'Detailed status description',
  },
  {
    id: 'equipment_type_id',
    column: 'equipment_type_id',
    label: 'Equipment',
    type: 'lookup',
    category: 'classification',
    description: 'Equipment type (Van, Flatbed, Reefer, etc)',
    lookup: {
      table: 'equipment_type',
      keyField: 'equipment_type_id',
      displayField: 'equipment_code',
      alternateField: 'equipment_name',
    },
    availableForGrouping: true,
    availableForAggregation: false,
  },
  {
    id: 'priority',
    column: 'priority',
    label: 'Priority',
    type: 'number',
    category: 'classification',
    description: 'Shipment priority level',
    availableForGrouping: true,
  },

  {
    id: 'created_date',
    column: 'created_date',
    label: 'Created Date',
    type: 'date',
    category: 'dates',
    description: 'When the shipment was created',
    availableForGrouping: true,
  },
  {
    id: 'modified_date',
    column: 'modified_date',
    label: 'Modified Date',
    type: 'date',
    category: 'dates',
    description: 'When the shipment was last modified',
  },
  {
    id: 'pickup_date',
    column: 'pickup_date',
    label: 'Pickup Date',
    type: 'date',
    category: 'dates',
    description: 'Scheduled pickup date',
    availableForGrouping: true,
    isDefault: true,
  },
  {
    id: 'delivery_date',
    column: 'delivery_date',
    label: 'Delivery Date',
    type: 'date',
    category: 'dates',
    description: 'Actual or scheduled delivery date',
    availableForGrouping: true,
  },
  {
    id: 'estimated_delivery_date',
    column: 'estimated_delivery_date',
    label: 'Est. Delivery',
    type: 'date',
    category: 'dates',
    description: 'Estimated delivery date',
  },
  {
    id: 'expected_delivery_date',
    column: 'expected_delivery_date',
    label: 'Expected Delivery',
    type: 'date',
    category: 'dates',
    description: 'Expected delivery date',
  },
  {
    id: 'requested_on_dock_date',
    column: 'requested_on_dock_date',
    label: 'Requested On Dock',
    type: 'date',
    category: 'dates',
    description: 'Requested arrival at dock date',
  },

  {
    id: 'retail',
    column: 'retail',
    label: 'Revenue',
    type: 'currency',
    category: 'financial',
    description: 'Customer charge amount (retail price)',
    availableForGrouping: false,
    availableForAggregation: true,
    defaultAggregation: 'sum',
    isDefault: true,
  },
  {
    id: 'retail_without_tax',
    column: 'retail_without_tax',
    label: 'Revenue (No Tax)',
    type: 'currency',
    category: 'financial',
    description: 'Customer charge excluding taxes',
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'cost',
    column: 'cost',
    label: 'Cost',
    type: 'currency',
    category: 'financial',
    description: 'Total carrier cost',
    adminOnly: true,
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'cost_without_tax',
    column: 'cost_without_tax',
    label: 'Cost (No Tax)',
    type: 'currency',
    category: 'financial',
    description: 'Carrier cost excluding taxes',
    adminOnly: true,
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'margin',
    column: 'margin',
    label: 'Margin',
    type: 'currency',
    category: 'financial',
    description: 'Profit margin (retail - cost)',
    adminOnly: true,
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'target_rate',
    column: 'target_rate',
    label: 'Target Rate',
    type: 'currency',
    category: 'financial',
    description: 'Internal target pricing',
    adminOnly: true,
  },
  {
    id: 'shipment_value',
    column: 'shipment_value',
    label: 'Declared Value',
    type: 'currency',
    category: 'financial',
    description: 'Declared value of goods for insurance',
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },

  {
    id: 'miles',
    column: 'miles',
    label: 'Miles',
    type: 'number',
    category: 'operational',
    description: 'Distance in miles',
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'number_of_pallets',
    column: 'number_of_pallets',
    label: 'Pallets',
    type: 'number',
    category: 'operational',
    description: 'Number of pallets',
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'linear_feet',
    column: 'linear_feet',
    label: 'Linear Feet',
    type: 'number',
    category: 'operational',
    description: 'Linear feet of trailer space',
    availableForAggregation: true,
    defaultAggregation: 'sum',
  },
  {
    id: 'is_stackable',
    column: 'is_stackable',
    label: 'Stackable',
    type: 'boolean',
    category: 'operational',
    description: 'Whether freight can be stacked',
    availableForGrouping: true,
  },
  {
    id: 'is_palletized',
    column: 'is_palletized',
    label: 'Palletized',
    type: 'boolean',
    category: 'operational',
    description: 'Whether freight is palletized',
    availableForGrouping: true,
  },
  {
    id: 'is_automated_ltl',
    column: 'is_automated_ltl',
    label: 'Automated LTL',
    type: 'boolean',
    category: 'operational',
    description: 'Auto-tendered to LTL carrier',
    availableForGrouping: true,
  },
  {
    id: 'created_by',
    column: 'created_by',
    label: 'Created By',
    type: 'string',
    category: 'operational',
    description: 'User who created the shipment',
    availableForGrouping: true,
  },
  {
    id: 'modified_by',
    column: 'modified_by',
    label: 'Modified By',
    type: 'string',
    category: 'operational',
    description: 'User who last modified the shipment',
    availableForGrouping: true,
  },
];

export const CUSTOMER_FIELDS: FieldDefinition[] = [
  {
    id: 'customer_id',
    column: 'customer_id',
    label: 'Customer ID',
    type: 'number',
    category: 'customer',
    description: 'Customer identifier',
    availableForGrouping: true,
    sourceTable: 'shipment',
  },
  {
    id: 'customer_name',
    column: 'company_name',
    label: 'Customer Name',
    type: 'string',
    category: 'customer',
    description: 'Customer company name',
    availableForGrouping: true,
    sourceTable: 'customer',
  },
  {
    id: 'external_customer_id',
    column: 'external_customer_id',
    label: 'External Customer ID',
    type: 'string',
    category: 'customer',
    description: 'External system customer identifier',
    sourceTable: 'customer',
  },
  {
    id: 'customer_is_active',
    column: 'is_active',
    label: 'Customer Active',
    type: 'boolean',
    category: 'customer',
    description: 'Whether customer is active',
    availableForGrouping: true,
    sourceTable: 'customer',
  },
  {
    id: 'customer_is_on_hold',
    column: 'is_on_hold',
    label: 'Customer On Hold',
    type: 'boolean',
    category: 'customer',
    description: 'Whether customer account is on hold',
    availableForGrouping: true,
    sourceTable: 'customer',
  },
];

export const CARRIER_FIELDS: FieldDefinition[] = [
  {
    id: 'carrier_name',
    column: 'carrier_name',
    label: 'Carrier',
    type: 'string',
    category: 'carrier',
    description: 'Carrier company name',
    availableForGrouping: true,
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'carrier_scac',
    column: 'carrier_scac',
    label: 'SCAC',
    type: 'string',
    category: 'carrier',
    description: 'Standard Carrier Alpha Code',
    availableForGrouping: true,
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'mc_number',
    column: 'mc_number',
    label: 'MC Number',
    type: 'string',
    category: 'carrier',
    description: 'Motor Carrier number',
    sourceTable: 'carrier',
  },
  {
    id: 'dot_number',
    column: 'dot_number',
    label: 'DOT Number',
    type: 'string',
    category: 'carrier',
    description: 'Department of Transportation number',
    sourceTable: 'carrier',
  },
  {
    id: 'carrier_account_number',
    column: 'account_number',
    label: 'Carrier Account',
    type: 'string',
    category: 'carrier',
    description: 'Account number with carrier',
    sourceTable: 'carrier',
  },
  {
    id: 'pro_number',
    column: 'pro_number',
    label: 'PRO #',
    type: 'string',
    category: 'carrier',
    description: 'Carrier PRO/tracking number',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'driver_name',
    column: 'driver_name',
    label: 'Driver Name',
    type: 'string',
    category: 'carrier',
    description: 'Assigned driver name',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'driver_phone',
    column: 'driver_phone',
    label: 'Driver Phone',
    type: 'string',
    category: 'carrier',
    description: 'Driver contact phone',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'truck_number',
    column: 'truck_number',
    label: 'Truck #',
    type: 'string',
    category: 'carrier',
    description: 'Truck/tractor number',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'trailer_number',
    column: 'trailer_number',
    label: 'Trailer #',
    type: 'string',
    category: 'carrier',
    description: 'Trailer number',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'assignment_status',
    column: 'assignment_status',
    label: 'Assignment Status',
    type: 'string',
    category: 'carrier',
    description: 'Carrier assignment status',
    availableForGrouping: true,
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'assigned_date',
    column: 'assigned_date',
    label: 'Assigned Date',
    type: 'date',
    category: 'carrier',
    description: 'When carrier was assigned',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'accepted_date',
    column: 'accepted_date',
    label: 'Accepted Date',
    type: 'date',
    category: 'carrier',
    description: 'When carrier accepted the load',
    sourceTable: 'shipment_carrier',
  },
  {
    id: 'carrier_pay',
    column: 'carrier_pay',
    label: 'Carrier Pay',
    type: 'currency',
    category: 'carrier',
    description: 'Amount paid to carrier',
    adminOnly: true,
    availableForAggregation: true,
    defaultAggregation: 'sum',
    sourceTable: 'shipment_carrier',
  },
];

export const LOCATION_FIELDS: FieldDefinition[] = [
  {
    id: 'origin_company_name',
    column: 'origin_company_name',
    label: 'Origin Company',
    type: 'string',
    category: 'locations',
    description: 'Pickup location company name',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_city',
    column: 'origin_city',
    label: 'Origin City',
    type: 'string',
    category: 'locations',
    description: 'Pickup location city',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_state',
    column: 'origin_state',
    label: 'Origin State',
    type: 'string',
    category: 'locations',
    description: 'Pickup location state',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
    isDefault: true,
  },
  {
    id: 'origin_postal_code',
    column: 'origin_postal_code',
    label: 'Origin Zip',
    type: 'string',
    category: 'locations',
    description: 'Pickup location ZIP code',
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_country',
    column: 'origin_country',
    label: 'Origin Country',
    type: 'string',
    category: 'locations',
    description: 'Pickup location country',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_contact_name',
    column: 'origin_contact_name',
    label: 'Origin Contact',
    type: 'string',
    category: 'locations',
    description: 'Pickup location contact name',
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_contact_phone',
    column: 'origin_contact_phone',
    label: 'Origin Phone',
    type: 'string',
    category: 'locations',
    description: 'Pickup location contact phone',
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_is_residential',
    column: 'origin_is_residential',
    label: 'Origin Residential',
    type: 'boolean',
    category: 'locations',
    description: 'Whether pickup is residential',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_appointment_time',
    column: 'origin_appointment_time',
    label: 'Origin Appointment',
    type: 'date',
    category: 'locations',
    description: 'Scheduled pickup appointment time',
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_arrival_time',
    column: 'origin_arrival_time',
    label: 'Origin Arrival',
    type: 'date',
    category: 'locations',
    description: 'Actual arrival at pickup',
    sourceTable: 'shipment_address',
  },
  {
    id: 'origin_departure_time',
    column: 'origin_departure_time',
    label: 'Origin Departure',
    type: 'date',
    category: 'locations',
    description: 'Actual departure from pickup',
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_company_name',
    column: 'destination_company_name',
    label: 'Destination Company',
    type: 'string',
    category: 'locations',
    description: 'Delivery location company name',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_city',
    column: 'destination_city',
    label: 'Destination City',
    type: 'string',
    category: 'locations',
    description: 'Delivery location city',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_state',
    column: 'destination_state',
    label: 'Destination State',
    type: 'string',
    category: 'locations',
    description: 'Delivery location state',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
    isDefault: true,
  },
  {
    id: 'destination_postal_code',
    column: 'destination_postal_code',
    label: 'Destination Zip',
    type: 'string',
    category: 'locations',
    description: 'Delivery location ZIP code',
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_country',
    column: 'destination_country',
    label: 'Destination Country',
    type: 'string',
    category: 'locations',
    description: 'Delivery location country',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_contact_name',
    column: 'destination_contact_name',
    label: 'Destination Contact',
    type: 'string',
    category: 'locations',
    description: 'Delivery location contact name',
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_contact_phone',
    column: 'destination_contact_phone',
    label: 'Destination Phone',
    type: 'string',
    category: 'locations',
    description: 'Delivery location contact phone',
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_is_residential',
    column: 'destination_is_residential',
    label: 'Destination Residential',
    type: 'boolean',
    category: 'locations',
    description: 'Whether delivery is residential',
    availableForGrouping: true,
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_appointment_time',
    column: 'destination_appointment_time',
    label: 'Destination Appointment',
    type: 'date',
    category: 'locations',
    description: 'Scheduled delivery appointment time',
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_arrival_time',
    column: 'destination_arrival_time',
    label: 'Destination Arrival',
    type: 'date',
    category: 'locations',
    description: 'Actual arrival at delivery',
    sourceTable: 'shipment_address',
  },
  {
    id: 'destination_departure_time',
    column: 'destination_departure_time',
    label: 'Destination Departure',
    type: 'date',
    category: 'locations',
    description: 'Actual departure from delivery',
    sourceTable: 'shipment_address',
  },
  {
    id: 'lane',
    column: 'lane',
    label: 'Lane',
    type: 'string',
    category: 'locations',
    description: 'Origin State to Destination State shipping lane',
    availableForGrouping: true,
    sourceTable: 'calculated',
  },
];

export const ITEM_FIELDS: FieldDefinition[] = [
  {
    id: 'description',
    column: 'description',
    label: 'Product Description',
    type: 'string',
    category: 'items',
    description: 'Product/item description - may contain product types',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'commodity',
    column: 'commodity',
    label: 'Commodity',
    type: 'string',
    category: 'items',
    description: 'Commodity type',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'total_weight',
    column: 'total_weight',
    label: 'Total Weight',
    type: 'number',
    category: 'items',
    description: 'Sum of item weights (lbs)',
    availableForAggregation: true,
    defaultAggregation: 'sum',
    sourceTable: 'shipment_item',
  },
  {
    id: 'total_quantity',
    column: 'total_quantity',
    label: 'Total Quantity',
    type: 'number',
    category: 'items',
    description: 'Sum of item quantities',
    availableForAggregation: true,
    defaultAggregation: 'sum',
    sourceTable: 'shipment_item',
  },
  {
    id: 'freight_class',
    column: 'freight_class',
    label: 'Freight Class',
    type: 'string',
    category: 'items',
    description: 'NMFC freight class',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'nmfc_code',
    column: 'nmfc_code',
    label: 'NMFC Code',
    type: 'string',
    category: 'items',
    description: 'NMFC item code',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'package_type',
    column: 'package_type',
    label: 'Package Type',
    type: 'string',
    category: 'items',
    description: 'Package type (pallet, box, crate, etc.)',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'sku',
    column: 'sku',
    label: 'SKU',
    type: 'string',
    category: 'items',
    description: 'Stock keeping unit',
    sourceTable: 'shipment_item',
  },
  {
    id: 'item_number',
    column: 'item_number',
    label: 'Item Number',
    type: 'string',
    category: 'items',
    description: 'Item/part number',
    sourceTable: 'shipment_item',
  },
  {
    id: 'is_hazmat',
    column: 'is_hazmat',
    label: 'Hazmat',
    type: 'boolean',
    category: 'items',
    description: 'Contains hazardous materials',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'hazmat_class',
    column: 'hazmat_class',
    label: 'Hazmat Class',
    type: 'string',
    category: 'items',
    description: 'Hazmat classification',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'hazmat_un_number',
    column: 'hazmat_un_number',
    label: 'Hazmat UN#',
    type: 'string',
    category: 'items',
    description: 'UN/NA identification number',
    sourceTable: 'shipment_item',
  },
  {
    id: 'item_is_stackable',
    column: 'is_stackable',
    label: 'Item Stackable',
    type: 'boolean',
    category: 'items',
    description: 'Item can be stacked',
    availableForGrouping: true,
    sourceTable: 'shipment_item',
  },
  {
    id: 'declared_value',
    column: 'declared_value',
    label: 'Item Declared Value',
    type: 'currency',
    category: 'items',
    description: 'Declared value for insurance',
    availableForAggregation: true,
    defaultAggregation: 'sum',
    sourceTable: 'shipment_item',
  },
];

export const ACCESSORIAL_FIELDS: FieldDefinition[] = [
  {
    id: 'accessorial_code',
    column: 'accessorial_code',
    label: 'Accessorial Code',
    type: 'string',
    category: 'accessorials',
    description: 'Accessorial service code',
    availableForGrouping: true,
    sourceTable: 'shipment_accessorial',
  },
  {
    id: 'accessorial_description',
    column: 'description',
    label: 'Accessorial',
    type: 'string',
    category: 'accessorials',
    description: 'Accessorial service description',
    availableForGrouping: true,
    sourceTable: 'shipment_accessorial',
  },
  {
    id: 'charge_amount',
    column: 'charge_amount',
    label: 'Charge Amount',
    type: 'currency',
    category: 'accessorials',
    description: 'Customer charge for accessorial',
    availableForAggregation: true,
    defaultAggregation: 'sum',
    sourceTable: 'shipment_accessorial',
  },
  {
    id: 'cost_amount',
    column: 'cost_amount',
    label: 'Cost Amount',
    type: 'currency',
    category: 'accessorials',
    description: 'Carrier cost for accessorial',
    adminOnly: true,
    availableForAggregation: true,
    defaultAggregation: 'sum',
    sourceTable: 'shipment_accessorial',
  },
];

export const ALL_FIELDS: FieldDefinition[] = [
  ...SHIPMENT_FIELDS,
  ...CUSTOMER_FIELDS,
  ...CARRIER_FIELDS,
  ...LOCATION_FIELDS,
  ...ITEM_FIELDS,
  ...ACCESSORIAL_FIELDS,
];

export const FIELD_CATEGORIES = [
  { id: 'identification', label: 'Identification', icon: 'Hash' },
  { id: 'classification', label: 'Classification', icon: 'Tag' },
  { id: 'dates', label: 'Dates', icon: 'Calendar' },
  { id: 'customer', label: 'Customer', icon: 'Building' },
  { id: 'locations', label: 'Locations', icon: 'MapPin' },
  { id: 'financial', label: 'Financial', icon: 'DollarSign' },
  { id: 'operational', label: 'Operational', icon: 'Truck' },
  { id: 'carrier', label: 'Carrier', icon: 'Truck' },
  { id: 'items', label: 'Items', icon: 'Package' },
  { id: 'accessorials', label: 'Accessorials', icon: 'Plus' },
] as const;

export const getFieldById = (id: string): FieldDefinition | undefined => {
  return ALL_FIELDS.find((f) => f.id === id);
};

export const getFieldByColumn = (column: string): FieldDefinition | undefined => {
  return ALL_FIELDS.find((f) => f.column === column);
};

export const getFieldsByCategory = (category: FieldCategory): FieldDefinition[] => {
  return ALL_FIELDS.filter((f) => f.category === category);
};

export const getGroupableFields = (): FieldDefinition[] => {
  return ALL_FIELDS.filter((f) => f.availableForGrouping);
};

export const getAggregatableFields = (): FieldDefinition[] => {
  return ALL_FIELDS.filter((f) => f.availableForAggregation);
};

export const getDefaultFields = (): FieldDefinition[] => {
  return ALL_FIELDS.filter((f) => f.isDefault);
};

export const getCustomerVisibleFields = (): FieldDefinition[] => {
  return ALL_FIELDS.filter((f) => !f.adminOnly);
};

export const getLookupFields = (): FieldDefinition[] => {
  return ALL_FIELDS.filter((f) => f.type === 'lookup' && f.lookup);
};
