/*
  # Create Report Files Storage Bucket
  
  1. New Storage Bucket
    - `report-files` - Stores generated PDF and CSV report files
    - Private bucket (not publicly accessible)
  
  2. Security Policies
    - Authenticated users can read files for their customer's reports
    - Service role can insert files (used by edge functions)
  
  3. Purpose
    - Stores scheduled report output files (PDF, CSV)
    - Files are generated by the run-scheduled-reports edge function
    - Users can download their reports from the Scheduled Reports page
*/

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'report-files',
  'report-files',
  false,
  52428800,
  ARRAY['application/pdf', 'text/csv', 'application/octet-stream']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Authenticated users can read report files"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'report-files');

CREATE POLICY "Service role can insert report files"
ON storage.objects FOR INSERT
TO service_role
WITH CHECK (bucket_id = 'report-files');

CREATE POLICY "Service role can update report files"
ON storage.objects FOR UPDATE
TO service_role
USING (bucket_id = 'report-files');

CREATE POLICY "Service role can delete report files"
ON storage.objects FOR DELETE
TO service_role
USING (bucket_id = 'report-files');